// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2TII6ZwSUHGHkwoQKhLYit7dFtaZLVSo',
    appId: '1:347021649198:web:43d057ef2f6996a62e46bf',
    messagingSenderId: '347021649198',
    projectId: 'flutter-login-functionality',
    authDomain: 'flutter-login-functionality.firebaseapp.com',
    storageBucket: 'flutter-login-functionality.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmwQUzsBKpPll_8wio6IRzcx4O__RHjXA',
    appId: '1:347021649198:android:26317bc20e2d0b272e46bf',
    messagingSenderId: '347021649198',
    projectId: 'flutter-login-functionality',
    storageBucket: 'flutter-login-functionality.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJCWnsVz4cH_p-oBKO4srTH5CA5-d1Hrg',
    appId: '1:347021649198:ios:25f04b47afc4d29c2e46bf',
    messagingSenderId: '347021649198',
    projectId: 'flutter-login-functionality',
    storageBucket: 'flutter-login-functionality.appspot.com',
    iosBundleId: 'com.example.flutterLoginFunctionality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJCWnsVz4cH_p-oBKO4srTH5CA5-d1Hrg',
    appId: '1:347021649198:ios:236a8d88d3f9e9082e46bf',
    messagingSenderId: '347021649198',
    projectId: 'flutter-login-functionality',
    storageBucket: 'flutter-login-functionality.appspot.com',
    iosBundleId: 'com.example.flutterLoginFunctionality.RunnerTests',
  );
}
